### ISSUE TITLE
PNG file size can be reduced 96%

### ISSUE THREAD

**Issue by vanderneut** [kulpreetchilana/Custom-iOS-Keyboards#10]
Hi Kulpreet, 

Impressive work! (I've not been entirely successful yet integrating it in my app, but that may be due to some project-setup specific issues on our site. Still trying to figure it out.)

Anyway, I just wanted to let you know (in case you didn't know yet), that if you run the images from this particular project through http://tinypng.com , that you will get a 96% file size reduction (or 12 MB total).

Thanks,
Erik

**Comment by vanderneut** [comment]
There's a pull request waiting for you if you're interested in pulling in these images with the smaller file size: https://github.com/kulpreetchilana/Custom-iOS-Keyboards/pull/12

Thanks,
Erik

**Comment by pjrobertson** [comment]
I think you can close this now, right? :)

Fixed in b6ad23f
